/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/adif/bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bands
         * @description ADIF's Band enumeration: name and frequency range in MHz, in frequency order.
         *     Curated view of `/adif/enumerations/band`.
         */
        get: operations["bands_api_v1_adif_bands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/contests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contests
         * @description ADIF's Contest_ID enumeration. Curated view of `/adif/enumerations/contest_id`.
         */
        get: operations["contests_api_v1_adif_contests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current
         * @description The lab-wide current ADIF version.
         */
        get: operations["current_api_v1_adif_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/datatypes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Datatypes
         * @description ADIF's data types (`datatypes.json`: GridSquare, Date, Number, ...).
         */
        get: operations["datatypes_api_v1_adif_datatypes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/dxcc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dxcc
         * @description ADIF's DXCC Entity Code enumeration, deleted entities included and marked.
         *     Curated view of `/adif/enumerations/dxcc_entity_code`.
         */
        get: operations["dxcc_api_v1_adif_dxcc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/enumerations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enumerations
         * @description Every ADIF enumeration, with its record count for the version (25 for ADIF 3.1.x), its
         *     canonical route segment (`table`) and the file ADIF publishes it as.
         */
        get: operations["enumerations_api_v1_adif_enumerations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/enumerations/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enumeration
         * @description One ADIF enumeration, with the columns ADIF defines for it. **The canonical route segment is
         *     the table name**, ADIF's name in lower case (e.g. `secondary_administrative_subdivision`), which
         *     is also the suffix of the file ADIF publishes it as; ADIF's own spelling
         *     (`Secondary_Administrative_Subdivision`) is accepted too, in any case. Anything else is 404.
         *
         *     Paged with `limit` / `offset`, searched with `q`, and **filtered exactly on any of its columns**
         *     by name, e.g. `?dxcc_entity_code=15&deleted=false`. A filter naming a column the enumeration
         *     does not have is refused (400) rather than ignored.
         */
        get: operations["enumeration_api_v1_adif_enumerations__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/enumerations/{name}/values/{column}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enumeration Values
         * @description The distinct values of one column of an enumeration, each with how many records carry it:
         *     e.g. which DXCC entities have primary subdivisions, and how many each. What a client needs to
         *     offer a filter on that column (`/adif/enumerations/<table>?<column>=<value>`). A column the
         *     enumeration does not have is 404. Values are text, ordered as the column orders them.
         */
        get: operations["enumeration_values_api_v1_adif_enumerations__name__values__column__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fields
         * @description ADIF's fields (`fields.json`): the vocabulary every IONIS-AI column is defined against.
         */
        get: operations["fields_api_v1_adif_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Modes
         * @description ADIF's Mode enumeration, each with its submodes (e.g. MFSK → FT4). A search matches submodes
         *     too, so `q=ft4` finds MFSK. Curated view of `/adif/enumerations/mode`.
         */
        get: operations["modes_api_v1_adif_modes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adif/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Releases
         * @description Every ADIF version loaded, with the SHA-256 of the adif.org file it was loaded from.
         */
        get: operations["releases_api_v1_adif_releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Which release this service runs. What the image says about itself: proof that a deployment
         *     runs a signed release is verifying the running image's digest (see SIGNING.md).
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Band */
        Band: {
            /** Band */
            band: string;
            /** Import Only */
            import_only: boolean;
            /** Lower Freq Mhz */
            lower_freq_mhz: number | null;
            /** Upper Freq Mhz */
            upper_freq_mhz: number | null;
        };
        /** Column */
        Column: {
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** ColumnValue */
        ColumnValue: {
            /** Count */
            count: number;
            /** Value */
            value: string | null;
        };
        /** Contest */
        Contest: {
            /** Contest Id */
            contest_id: string;
            /** Description */
            description: string | null;
            /** Import Only */
            import_only: boolean;
        };
        /** Current */
        Current: {
            /** Adif Version */
            adif_version: string;
            /**
             * Set At
             * Format: date-time
             */
            set_at: string;
        };
        /** DataType */
        DataType: {
            /** Data Type Indicator */
            data_type_indicator: string | null;
            /** Data Type Name */
            data_type_name: string;
            /** Description */
            description: string | null;
            /** Import Only */
            import_only: boolean;
            /** Maximum Value */
            maximum_value: string | null;
            /** Minimum Value */
            minimum_value: string | null;
        };
        /** DxccEntity */
        DxccEntity: {
            /** Deleted */
            deleted: boolean;
            /** Entity Code */
            entity_code: number;
            /** Entity Name */
            entity_name: string;
        };
        /** Enumeration */
        Enumeration: {
            /** Adif Version */
            adif_version: string;
            /** Columns */
            columns: components["schemas"]["Column"][];
            /** File */
            file: string;
            /** Limit */
            limit: number | null;
            /** Name */
            name: string;
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Table */
            table: string;
            /** Total */
            total: number;
        };
        /** EnumerationSummary */
        EnumerationSummary: {
            /** File */
            file: string;
            /** Import Only Records */
            import_only_records: number;
            /** Name */
            name: string;
            /** Records */
            records: number;
            /** Table */
            table: string;
        };
        /** Field */
        Field: {
            /** Data Type */
            data_type: string;
            /** Description */
            description: string | null;
            /** Enumeration */
            enumeration: string | null;
            /** Field Name */
            field_name: string;
            /** Import Only */
            import_only: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** Mode */
        Mode: {
            /** Description */
            description: string | null;
            /** Import Only */
            import_only: boolean;
            /** Mode */
            mode: string;
            /** Submodes */
            submodes: string[];
        };
        /** Release */
        Release: {
            /** Adif Version */
            adif_version: string;
            /** Released */
            released: string | null;
            /** Source Sha256 */
            source_sha256: string;
            /** Source Url */
            source_url: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Version
         * @description The release this service runs: version e.g. "0.1.2" and the git revision it was built from.
         *     "dev" / "unknown" for anything not built by the publish script.
         */
        Version: {
            /** Revision */
            revision: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bands_api_v1_adif_bands_get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
                /** @description Rows per page, 1 to 1000. Omit to get every row (the pre-R15 behaviour). */
                limit?: number | null;
                /** @description Rows to skip, for the page after `limit` rows. */
                offset?: number;
                /** @description Case-insensitive text search across the listed columns, applied before paging. */
                q?: string | null;
                /** @description Only the band containing this frequency in MHz (lower ≤ f ≤ upper), e.g. 14.074 → 20m. */
                freq_mhz?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Present while more rows remain: `<url>; rel="next"` */
                    Link?: string;
                    /** @description Rows matching the filters, across all pages */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Band"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contests_api_v1_adif_contests_get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
                /** @description Rows per page, 1 to 1000. Omit to get every row (the pre-R15 behaviour). */
                limit?: number | null;
                /** @description Rows to skip, for the page after `limit` rows. */
                offset?: number;
                /** @description Case-insensitive text search across the listed columns, applied before paging. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Present while more rows remain: `<url>; rel="next"` */
                    Link?: string;
                    /** @description Rows matching the filters, across all pages */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_api_v1_adif_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Current"];
                };
            };
        };
    };
    datatypes_api_v1_adif_datatypes_get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
                /** @description Rows per page, 1 to 1000. Omit to get every row (the pre-R15 behaviour). */
                limit?: number | null;
                /** @description Rows to skip, for the page after `limit` rows. */
                offset?: number;
                /** @description Case-insensitive text search across the listed columns, applied before paging. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Present while more rows remain: `<url>; rel="next"` */
                    Link?: string;
                    /** @description Rows matching the filters, across all pages */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataType"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dxcc_api_v1_adif_dxcc_get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
                /** @description Rows per page, 1 to 1000. Omit to get every row (the pre-R15 behaviour). */
                limit?: number | null;
                /** @description Rows to skip, for the page after `limit` rows. */
                offset?: number;
                /** @description Case-insensitive text search across the listed columns, applied before paging. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Present while more rows remain: `<url>; rel="next"` */
                    Link?: string;
                    /** @description Rows matching the filters, across all pages */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DxccEntity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enumerations_api_v1_adif_enumerations_get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumerationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enumeration_api_v1_adif_enumerations__name__get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
                /** @description Rows per page, 1 to 1000. Omit to get every row (the pre-R15 behaviour). */
                limit?: number | null;
                /** @description Rows to skip, for the page after `limit` rows. */
                offset?: number;
                /** @description Case-insensitive text search across the listed columns, applied before paging. */
                q?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Present while more rows remain: `<url>; rel="next"` */
                    Link?: string;
                    /** @description Rows matching the filters, across all pages */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enumeration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enumeration_values_api_v1_adif_enumerations__name__values__column__get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
                /** @description Rows per page, 1 to 1000. Omit to get every row (the pre-R15 behaviour). */
                limit?: number | null;
                /** @description Rows to skip, for the page after `limit` rows. */
                offset?: number;
                /** @description Case-insensitive text search across the listed columns, applied before paging. */
                q?: string | null;
            };
            header?: never;
            path: {
                name: string;
                column: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Present while more rows remain: `<url>; rel="next"` */
                    Link?: string;
                    /** @description Rows matching the filters, across all pages */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnValue"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fields_api_v1_adif_fields_get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
                /** @description Rows per page, 1 to 1000. Omit to get every row (the pre-R15 behaviour). */
                limit?: number | null;
                /** @description Rows to skip, for the page after `limit` rows. */
                offset?: number;
                /** @description Case-insensitive text search across the listed columns, applied before paging. */
                q?: string | null;
                /** @description Only fields of this ADIF data type, exactly, e.g. Enumeration. */
                data_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Present while more rows remain: `<url>; rel="next"` */
                    Link?: string;
                    /** @description Rows matching the filters, across all pages */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Field"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modes_api_v1_adif_modes_get: {
        parameters: {
            query?: {
                /** @description ADIF version, e.g. 3.1.7. Defaults to the lab's current version. */
                adif_version?: string | null;
                /** @description Rows per page, 1 to 1000. Omit to get every row (the pre-R15 behaviour). */
                limit?: number | null;
                /** @description Rows to skip, for the page after `limit` rows. */
                offset?: number;
                /** @description Case-insensitive text search across the listed columns, applied before paging. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Present while more rows remain: `<url>; rel="next"` */
                    Link?: string;
                    /** @description Rows matching the filters, across all pages */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    releases_api_v1_adif_releases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"][];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
}
